# Generated by Django 5.2.4 on 2025-07-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('tipo_documento', models.CharField(max_length=10)),
                ('documento', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('producto', models.CharField(max_length=20)),
                ('poliza', models.CharField(max_length=50)),
                ('periodo', models.CharField(max_length=5)),
                ('valor_asegurado', models.CharField(max_length=50)),
                ('valor_prima', models.CharField(max_length=50)),
                ('doc_cobro', models.CharField(max_length=50)),
                ('fecha_ini', models.CharField(max_length=20)),
                ('fecha_fin', models.CharField(max_length=20)),
                ('dias', models.CharField(max_length=10)),
                ('telefono_1', models.CharField(max_length=20)),
                ('telefono_2', models.CharField(max_length=20)),
                ('telefono_3', models.CharField(max_length=20)),
                ('ciudad', models.CharField(max_length=50)),
                ('departamento', models.CharField(max_length=50)),
                ('fecha_venta', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.CharField(max_length=20)),
                ('tipo_trans', models.CharField(max_length=10)),
                ('beneficiarios', models.TextField()),
                ('genero', models.CharField(max_length=10)),
                ('sucursal', models.CharField(max_length=50)),
                ('tipo_cuenta', models.CharField(max_length=20)),
                ('ultimos_digitos_cuenta', models.CharField(max_length=10)),
                ('entidad_bancaria', models.CharField(max_length=50)),
                ('nombre_banco', models.CharField(max_length=50)),
                ('estado_debito', models.CharField(max_length=20)),
                ('causal_rechazo', models.CharField(max_length=100)),
                ('codigo_canal', models.CharField(max_length=20)),
                ('descripcion_canal', models.CharField(max_length=100)),
                ('codigo_estrategia', models.CharField(max_length=20)),
                ('tipo_estrategia', models.CharField(max_length=20)),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True)),
                ('fecha_entrega_colmena', models.CharField(max_length=20)),
                ('mes_a_trabajar', models.CharField(max_length=20)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre_db', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=5)),
                ('whatsapp', models.CharField(max_length=5)),
                ('texto', models.CharField(max_length=5)),
                ('email', models.CharField(max_length=5)),
                ('fisica', models.CharField(max_length=5)),
                ('mejor_canal', models.CharField(max_length=20)),
                ('contactar_al', models.CharField(max_length=100)),
            ],
        ),
    ]
